
name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Test
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/NinjaCsv/NinjaCsv.csproj
    - name: Build
      run: dotnet build src/NinjaCsv/NinjaCsv.csproj --configuration Release --no-restore 
    - name: Test
      run: dotnet test src/NinjaCsv.UnitTests/NinjaCsv.UnitTests.csproj --no-restore --verbosity normal 
